# Generated by Django 6.0.4 on 2026-04-22 03:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('age_years', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Idade')),
                ('profession', models.CharField(max_length=120, verbose_name='Profissão')),
                ('consultation_reason', models.TextField(verbose_name='Motivo da Consulta')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso Atual (kg)')),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Altura (cm)')),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IMC')),
                ('sleep_quality', models.PositiveSmallIntegerField(verbose_name='Qualidade do Sono (1-5)')),
                ('anxiety_level', models.PositiveSmallIntegerField(verbose_name='Nível de Ansiedade (1-5)')),
                ('stress_level', models.PositiveSmallIntegerField(verbose_name='Nível de Estresse (1-5)')),
                ('does_physical_activity', models.BooleanField(default=False, verbose_name='Pratica Atividade Física?')),
                ('activity_modality', models.CharField(blank=True, max_length=120, null=True, verbose_name='Modalidade')),
                ('activity_weekly_frequency', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Frequência Semanal')),
                ('activity_workout_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='Horário do Treino')),
                ('activity_duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Duração (min)')),
                ('uses_supplement', models.BooleanField(default=False, verbose_name='Usa Suplemento?')),
                ('supplements', models.TextField(blank=True, null=True, verbose_name='Quais suplementos')),
                ('recall_breakfast', models.TextField(verbose_name='Café da Manhã')),
                ('recall_lunch', models.TextField(verbose_name='Almoço')),
                ('recall_snack', models.TextField(verbose_name='Lanche')),
                ('recall_dinner', models.TextField(verbose_name='Jantar')),
                ('recall_supper_other', models.TextField(verbose_name='Ceia/Outros')),
                ('additional_observations', models.TextField(blank=True, null=True, verbose_name='Observações Adicionais')),
                ('notification_status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('failed', 'Falha')], default='pending', max_length=20, verbose_name='Status da Notificação')),
            ],
            options={
                'verbose_name': 'Anamnese',
                'verbose_name_plural': 'Anamneses',
                'ordering': ['-created_at'],
            },
        ),
    ]
