# Generated by Django 6.0.4 on 2026-04-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamneses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anamnese',
            name='birth_date',
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='age_years',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Idade'),
            preserve_default=False,
        ),
    ]
